name: Daily_bot

on: 
    push:
    schedule:
        - cron: '*/6 * * * *'



jobs:
    Daily-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run App
              run: python one.py           
            
        

     
