name: Daily_bot

on: 
    push:
    schedule:
        - cron: '0 15 * * *'



jobs:
    Daily-Run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt 
            - name: Run App
              run: python one.py    
            - name: Upload screenshots
              uses: actions/upload-artifact@latest
              if: failure()
              with:
                  name: cypress-snapshots
                  path: test1
            
        

     
